### ISSUE TITLE
chore: remove run command from tests-on-pr.yml when gooey is available on conda-forge

### ISSUE THREAD

**Issue by zmx27** [regro/regolith#1262]
### Problem

In ```tests-on-pr.yml```, we currently plan to use the reusable workflow script from ```scikit-package``` along with running a command that pip installs ```gooey```. Here is how it looks:
```
name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: regolith
      c_extension: false
      headless: false
      run: pip install gooey
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

### Proposed solution
Once a new```gooey``` that supports the latest versions of Python is ready to be installed from conda-forge, remove the above run command and instead add ```gooey``` to ```requirements/conda.txt```.
