### ISSUE TITLE
ENH: l_projecta print in a verbose way when -v is specified

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#483]
related to #480 #481 #482 
Current behavior:
-v is accepted but has no action

Desired behavior:
-v printout looks something like 
```
20mw_grant_lister:
    status: finished, begin_date: 2020-05-28 due_date: 2020-06-23 end_date 2020-06-18 grant: dmref19
    description: Regolith lister for grants
    team: 
        lead: mwinitch
        group_members: aejaz, sstao
        collaborators: dnocera (harvard)
```
