### ISSUE TITLE
ENH: extend get_dates to take an optional name for the date field

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#521]
current behavior:
get_dates looks for day, month, year, date, and also begin_ and end_ day/month/year/date

desired behavior:
the same as before, but optionally I can supply an argument ``date_field_prefix``.  Then get_dates still searches for begin and end date as before, but instead of looking for day/month/year/date it looks for ``<date_field_prefix>_day/month/year/date``.

example:
```
get_dates(proposals, date_field_prefix="submission")
```
will treat ``submission_day`` as it would ``day``, ``submission_month`` as it would ``month`` and so on.

**Comment by mwinitch** [comment]
@sbillinge Could you give an example of this? What would be a possible input for `date_field_prefix` for some given element that can be dated.

**Comment by sbillinge** [comment]
> 
> 
> @sbillinge Could you give an example of this? What would be a possible input for `date_field_prefix` for some given element that can be dated.

The specific need right now can be found in the collection ``expenses`` and in ``reimbursements`` dict there is a submission day/month/year/date that I need to retrieve....
```
  reimbursements:
    - amount: 157.98
      day: 0
      month: 0
      submission_day: 5
      submission_month: 7
      submission_year: 2020
      where: Sherry
      year: 2020
  status: submitted
```
but once I have this I will use it more broadly rather than having to guess what a date means in a certain context.  In this reimbursement case, for example, the day/month/year/date is really a "reimbursement" date.
