### ISSUE TITLE
ENH: verbose contact output format change

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#530]
Thanks so much for the verbose output on the contacts.   Please could we format it like this though?
```
Simon J. L. Billinge
    id: sbillinge
    email: sb2896@columbia.edu
    institution: Columbia University
    department: Applied Physics and Applied Mathematics
    notes:
      - old fart
      - grumpy
    aka:
      - Billinge, Simon
```
and this for a short one
```
Simon J. L. Billinge
    id: sbillinge
    institution: Columbia University
```
